#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling and linting project before committing'

#Prettier styling forcing.
yarn lint-staged

# If everything passes... Now we can commit
echo '✅✅✅✅ All Good. Committing changes now. ✅✅✅✅'
