export enum ActionTypes {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGGEDIN_USER_DATA = 'LOGGEDIN_USER_DATA',
  SET_GENERAL_SETTINGS = 'SET_GENERAL_SETTINGS',
  SET_MISCELLANEOUS_DATA = 'SET_MISCELLANEOUS_DATA',
}
